// Decompiled with JetBrains decompiler
// Type: YoutubeExplode.Models.ClosedCaptions.ClosedCaptionTrackInfo
// Assembly: Explode, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
// MVID: D9BD94EC-1F8A-4D23-A0FC-F2CF6230133A
// Assembly location: C:\Users\Admin\Desktop\re\Tube Free for WP v.1.6.8.0\Explode.dll

using JetBrains.Annotations;
using YoutubeExplode.Internal;

namespace YoutubeExplode.Models.ClosedCaptions
{
  public class ClosedCaptionTrackInfo
  {
    [NotNull]
    public string Url { get; }

    [NotNull]
    public Language Language { get; }

    public bool IsAutoGenerated { get; }

    public ClosedCaptionTrackInfo(string url, Language language, bool isAutoGenerated)
    {
      this.Url = url.GuardNotNull<string>(nameof (url));
      this.Language = language.GuardNotNull<Language>(nameof (language));
      this.IsAutoGenerated = isAutoGenerated;
    }

    public override string ToString() => string.Format("{0}", new object[1]
    {
      (object) this.Language
    });
  }
}
